version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "enterprisebus"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1b88wl6ohyg73"
s3_prefix = "enterprisebus"
region = "us-east-1"
profile = "yaron"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
